---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/feed
  label: Feed
  create: documents
  match: "**/*"
  exclude: "*.json"
upload_dir: src/img/feed
public_path: public/img/feed
front_matter_path: "/img/feed"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
